name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - cudatoolkit=11.8
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  - pytorch
  - torchaudio
  - torchvision
  - pytorch-cuda=11.8

  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn